#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Copyright (c) 2019-2025 guanguans<ityaozm@gmail.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 *
 * @see https://github.com/guanguans/soar-php
 */

use Composer\InstalledVersions;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Process\ExecutableFinder;
use Symfony\Component\Process\PhpExecutableFinder;
use Symfony\Component\Process\Process;

require __DIR__.'/vendor/autoload.php';
file_exists($autoload = __DIR__.'/../../vendor/autoload.php') and require $autoload;

/** @noinspection PhpUnhandledExceptionInspection */
/** @noinspection DuplicatedCode */
$status = (new SingleCommandApplication)
    ->setName('Composer Updater')
    ->addOption('composer-json-path', null, InputOption::VALUE_OPTIONAL)
    ->addOption('highest-php-binary', null, InputOption::VALUE_REQUIRED)
    ->addOption('composer-binary', null, InputOption::VALUE_OPTIONAL)
    ->addOption('except-package', null, InputOption::VALUE_IS_ARRAY | InputOption::VALUE_OPTIONAL)
    ->addOption('except-dependency-version', null, InputOption::VALUE_IS_ARRAY | InputOption::VALUE_OPTIONAL)
    ->setCode(function (InputInterface $input, OutputInterface $output): void {
        assert_options(\ASSERT_BAIL, 1);
        \assert($this instanceof SingleCommandApplication);
        \assert((bool) $input->getOption('highest-php-binary'));

        (new class(
            $input->getOption('composer-json-path') ?: __DIR__.'/composer.json',
            $input->getOption('highest-php-binary'),
            $input->getOption('composer-binary'),
            $input->getOption('except-package'),
            $input->getOption('except-dependency-version'),
            new SymfonyStyle($input, $output),
        ) {
            private readonly string $composerJsonPath;
            private readonly string $highestComposerBinary;
            private readonly string $composerBinary;

            /** @var list<string> */
            private readonly array $exceptPackages;

            /** @var list<string> */
            private readonly array $exceptDependencyVersions;
            private readonly SymfonyStyle $symfonyStyle;

            /**
             * @noinspection ParameterDefaultsNullInspection
             */
            public function __construct(
                string $composerJsonPath,
                ?string $highestPhpBinary = null,
                ?string $composerBinary = null,
                array $exceptPackages = [],
                array $exceptDependencyVersions = [],
                ?SymfonyStyle $symfonyStyle = null
            ) {
                assert_options(\ASSERT_BAIL, 1);
                \assert((bool) $composerJsonPath);

                $this->composerJsonPath = realpath($composerJsonPath);
                $this->highestComposerBinary = $this->getComposerBinary($composerBinary, $highestPhpBinary);
                $this->composerBinary = $this->getComposerBinary($composerBinary);
                $this->exceptPackages = ['ext-*', 'php', 'psr/*', ...$exceptPackages];
                $this->exceptDependencyVersions = ['\*', '*-*', '*@*', ...$exceptDependencyVersions];
                $this->symfonyStyle = $symfonyStyle ?? new SymfonyStyle(new ArgvInput, new ConsoleOutput);
            }

            /**
             * @noinspection NullPointerExceptionInspection
             */
            public function __invoke(): void
            {
                $this
                    ->updateComposerPackages()
                    ->updateOutdatedComposerPackages()
                    ->updateComposerPackages()
                    ->updateOutdatedComposerPackages()
                    ->updateComposerPackages()
                    // ->normalizeComposerJson()
                    ->success();
            }

            private function updateComposerPackages(): self
            {
                $this->mustRunCommand("$this->composerBinary update --with-all-dependencies");

                return $this;
            }

            /**
             * @return $this|never-return
             */
            private function updateOutdatedComposerPackages(): self
            {
                $outdatedComposerJsonContents = json_encode(
                    $this->getOutdatedDecodedComposerJson(),
                    \JSON_PRETTY_PRINT | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES
                ).\PHP_EOL;

                file_put_contents($this->composerJsonPath, $outdatedComposerJsonContents);

                return $this;
            }

            /**
             * @noinspection PhpUnusedPrivateMethodInspection
             */
            private function normalizeComposerJson(): self
            {
                $this->mustRunCommand("$this->composerBinary normalize --diff");

                return $this;
            }

            private function success(): void
            {
                $this->symfonyStyle->success('Composer packages updated successfully!');
            }

            /**
             * @noinspection LongLine
             * @noinspection D
             * @noinspection PhpMultipleClassDeclarationsInspection
             */
            private function getOutdatedDecodedComposerJson(): array
            {
                $outdatedComposerPackages = $this->getOutdatedComposerPackages();
                $decodedComposerJson = json_decode(file_get_contents($this->composerJsonPath), true, 512, \JSON_THROW_ON_ERROR);
                InstalledVersions::reload([]);

                foreach ($decodedComposerJson as $name => &$value) {
                    if (!\in_array($name, ['require', 'require-dev'], true)) {
                        continue;
                    }

                    foreach ($value as $package => &$dependencyVersion) {
                        if (
                            Str::is($this->exceptPackages, $package)
                            || Str::is($this->exceptDependencyVersions, $dependencyVersion)
                        ) {
                            continue;
                        }

                        if ($version = InstalledVersions::getVersion($package)) {
                            $dependencyVersion = $this->toDependencyVersion($version);
                        }

                        if (isset($outdatedComposerPackages[$package])) {
                            $dependencyVersion = $outdatedComposerPackages[$package]['dependency_version'];
                        }
                    }
                }

                return $decodedComposerJson;
            }

            private function getOutdatedComposerPackages(): array
            {
                return array_reduce(
                    json_decode(
                        substr(
                            $output = $this
                                ->mustRunCommand("$this->highestComposerBinary outdated --format=json --direct")
                                ->getOutput(),
                            (int) strpos($output, '{'.\PHP_EOL)
                        ),
                        true,
                        512,
                        \JSON_THROW_ON_ERROR
                    )['installed'],
                    function (array $carry, array $package): array {
                        $lowestArrayVersion = $this->toArrayVersion($package['version']);
                        $highestArrayVersion = $this->toArrayVersion($package['latest']);
                        $dependencyVersions = [
                            $this->toDependencyVersion($package['version']),
                            ...match (true) {
                                $lowestArrayVersion[0] === $highestArrayVersion[0]
                                && $lowestArrayVersion[1] < $highestArrayVersion[1] => array_map(
                                    static fn (string $minor): string => "^$lowestArrayVersion[0].$minor",
                                    range($lowestArrayVersion[1] + 1, $highestArrayVersion[1])
                                ),
                                $lowestArrayVersion[0] < $highestArrayVersion[0] => array_map(
                                    static fn (string $major): string => "^$major.0",
                                    range($lowestArrayVersion[0] + 1, $highestArrayVersion[0])
                                ),
                                default => []
                            },
                        ];

                        sort($dependencyVersions);

                        $package['dependency_version'] = implode(' || ', $dependencyVersions);
                        $carry[$package['name']] = $package;

                        return $carry;
                    },
                    []
                );
            }

            private function getComposerBinary(?string $composerBinary = null, ?string $phpBinary = null): string
            {
                return \sprintf(
                    '%s %s',
                    escapeshellarg($phpBinary ?? (new PhpExecutableFinder)->find()),
                    escapeshellarg((string) ($composerBinary ?? (new ExecutableFinder)->find('composer')))
                );
            }

            /**
             * @noinspection PhpSameParameterValueInspection
             * @noinspection LongLine
             *
             * @param mixed $input The input as stream resource, scalar or \Traversable, or null for no input
             */
            private function mustRunCommand(
                array|string $command,
                ?string $cwd = null,
                array $env = [],
                mixed $input = null,
                ?float $timeout = 600
            ): Process {
                $additionalOptions = [
                    '--no-interaction',
                    '--no-plugins',
                    '--no-scripts',
                    '--ansi',
                ];
                $cwd ??= \dirname($this->composerJsonPath);
                $env += ['COMPOSER_MEMORY_LIMIT' => -1];

                $process = \is_string($command)
                    ? Process::fromShellCommandline(\sprintf("$command %s", implode(' ', $additionalOptions)), $cwd, $env, $input, $timeout)
                    : new Process($command + $additionalOptions, $cwd, $env, $input, $timeout);

                $this->symfonyStyle->warning($process->getCommandLine());

                return $process->mustRun(function (string $type, string $buffer): void {
                    $this->symfonyStyle->isVerbose() and $this->symfonyStyle->write($buffer);
                });
            }

            private function toDependencyVersion(string $version): string
            {
                return '^'.implode('.', \array_slice($this->toArrayVersion($version), 0, 2));
            }

            private function toArrayVersion(string $version): array
            {
                return explode('.', ltrim($version, 'v'));
            }
        })();
    })
    ->run();

exit($status);
