#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Copyright (c) 2021-2025 guanguans<ityaozm@gmail.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 *
 * @see https://github.com/guanguans/laravel-skeleton
 */

namespace RuleDocGenerator202408;

require __DIR__.'/vendor/autoload.php';

require __DIR__.'/vendor-bin/common/vendor/symplify/rule-doc-generator/bin/rule-doc-generator.php';
