style: github
# https://github.com/garden-io/garden
# https://github.com/git-chglog/git-chglog
# https://github.com/quay/clair
# https://github.com/muzilib/commit-template-idea-plugin/blob/main/src/main/resources/i18n/data_en_US.properties#L22
# https://github.com/fobgochod/git-commit-message-format/blob/main/src/main/resources/messages/GitBundle.properties#L37
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/guanguans/soar-php
options:
  commits:
    filters:
      Type:
        - build
        # - chore
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - style
        - test
  commit_groups:
    title_maps:
      build: Builds
      chore: Chores
      ci: Continuous Integrations
      docs: Documents
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactorings
      revert: Reverts
      style: Styles
      test: Tests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
